### ISSUE TITLE
Fatal Error: Module (ZF2AuthAcl) could not be initialized

### ISSUE THREAD

**Issue by wilcori** [Mohit-Singh/ZF2AuthAcl#1]
I try to use the exemplo but I get this error, if you could help me please.

in application.config.php I have configured the module:

```
'modules' => array(
    'Application',
    'ZF2AuthAcl',
    // 'Album',
),
```

I do not understand it is aclAuth.local.php:

```
   'ACL_Template' => 'zf2-auth-acl/index/permission.phtml',
```

.
.
       'defaultRaoleId' => 'MEMBER', //<- este usuario esta creado
.
.
        'globalList' => array(
              'Application\Controller\Index-index' //<- esto me huele mal
       ),
.
.

Help Please

the complet error is:

Fatal error: Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException' with message 'Module (ZF2AuthAcl) could not be initialized.' in /var/www/html/autenticate/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php:175 Stack trace: #0 /var/www/html/autenticate/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php(149): Zend\ModuleManager\ModuleManager->loadModuleByName(Object(Zend\ModuleManager\ModuleEvent)) #1 /var/www/html/autenticate/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php(90): Zend\ModuleManager\ModuleManager->loadModule('ZF2AuthAcl') #2 [internal function]: Zend\ModuleManager\ModuleManager->onLoadModules(Object(Zend\ModuleManager\ModuleEvent)) #3 /var/www/html/autenticate/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\ModuleManager\ModuleEvent)) #4 /var/www/html/autenticate/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.p in /var/www/html/autenticate/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php on line 175

**Comment by Mohit-Singh** [comment]
Hi Wilcori, 
sorry for late response , still this issue is coming at your end??
if yes, can you please tell me how you include this module in your application ???

**Comment by Mohit-Singh** [comment]
No further information provided.
